name: cmake-find-package
description: |
  Validates presence and findability of a library in a docker image using ajakhotia/importTester

inputs:
  library-name:
    description: 'Library to test. This is forwarded as to find_package(... REQUIRED) call in cmake'
    required: true

  prefix-path:
    description: 'A ; delimited string containing prefix paths of where the library might exist in the image.'
    required: false

  image-name:
    description: 'Fully qualified image name (e.g. ghcr.io/owner/repo/build/stage).'
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout-import-tester
      uses: actions/checkout@v6
      with:
        repository: ajakhotia/importTester
        path: importTester
        ref: main

    - name: find-library
      id: find-library
      shell: bash
      run: |
        docker run --rm                                                         \
          --volume ./importTester:/tmp/importTester-src                         \
          ${{ inputs.image-name }}                                              \
          bash -c '                                                             \
            cmake -S /tmp/importTester-src                                      \
              -B /tmp/importTester-build                                        \
              -DCMAKE_PREFIX_PATH:STRING="${{ inputs.prefix-path }}"            \
              -DIMPORT_TESTER_PACKAGE_LIST:STRING="${{ inputs.library-name }}"  \
          '
