set(CMAKE_HOST_SYSTEM_NAME "Linux")
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
set(CMAKE_Fortran_COMPILER /usr/bin/flang)

find_program(NVCC_EXECUTABLE nvcc HINTS ENV CUDA_HOME ENV CUDA_PATH /usr/local/cuda PATH_SUFFIXES bin)

if(NVCC_EXECUTABLE)
  set(CMAKE_CUDA_COMPILER "${NVCC_EXECUTABLE}")
  set(CMAKE_CUDA_ARCHITECTURES all)
  set(CMAKE_CUDA_HOST_COMPILER ${CMAKE_CXX_COMPILER})
  set(CMAKE_CUDA_FLAGS_INIT "${CMAKE_CUDA_FLAGS_INIT} -allow-unsupported-compiler")
endif()
