#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------
# Registers upstream apt sources ("taps") that track the latest
# releases of the toolchain vendors this infrastructure uses:
#
#   gnu       Ubuntu Toolchain PPA / Debian backports (GCC)
#   llvm      apt.llvm.org (Clang/LLVM)
#   nvidia    NVIDIA CUDA repository
#   kitware   apt.kitware.com (CMake)
#
# Each tap registers a source and its signing key using the
# vendor's own supported mechanism, and nothing else. Package
# selection lives with the caller (see extractDependencies.sh);
# run 'apt-get update' after this script before installing.
# ------------------------------------------------------------

readonly ALL_TAPS=(gnu llvm nvidia kitware)

usage() {
  cat << 'EOF'
Usage: addAptSources.sh [-y] [TAP ...]

Registers upstream apt sources for the requested taps. With no
taps named, all of them are set up: gnu llvm nvidia kitware.
Naming one or more taps restricts the run to just those.

Options:
  -y   Assume "yes" to all prompts (non-interactive).
  -h   Show this help.
EOF
}

fail() {
  echo "$@" >&2
  exit 1
}

# ---------------------------------------------------------------- helpers ----

# Prints the raw vendor index page for callers to grep. Prints nothing when
# the page cannot be fetched, so callers see that as "no entries found".
fetch_index() {
  local url="$1"
  curl -fsSL --compressed "${url}" || true
}

# Installs a dearmored copy of the given public key at the given path.
install_signing_key() {
  local key_url="$1"
  local keyring_path="$2"
  install -d -m 0755 "$(dirname "${keyring_path}")"
  curl -fsSL "${key_url}" | gpg --dearmor --yes -o "${keyring_path}"
  chmod 0644 "${keyring_path}"
}

# ------------------------------------------------------------------- taps ----

tap_gnu() {
  if [[ "${distro_id}" == "debian" ]]; then
    if [[ "${codename}" == "sid" ]]; then
      echo "gnu: Debian sid already tracks the latest GCC. Nothing to do."
      return 0
    fi
    local suite="${codename}-backports"
    local keyring="/usr/share/keyrings/debian-archive-keyring.gpg"
    echo "gnu: Enabling Debian backports (${suite})..."
    printf 'deb [signed-by=%s] https://deb.debian.org/debian %s main\n' \
      "${keyring}" "${suite}" > "/etc/apt/sources.list.d/${suite}.list"
    return 0
  fi

  echo "gnu: Adding the Ubuntu Toolchain PPA (ubuntu-toolchain-r/test)..."
  add-apt-repository -y -n ppa:ubuntu-toolchain-r/test
}

tap_llvm() {
  local host="https://apt.llvm.org"
  local keyring="/etc/apt/keyrings/llvm-archive-keyring.gpg"
  local sources_file="/etc/apt/sources.list.d/llvm-toolchain.list"

  # apt.llvm.org publishes one suite per LLVM major per distro release
  # (llvm-toolchain-<codename>-<major>, plus an unversioned snapshot suite).
  # Discover the suites that exist for this release instead of hardcoding a
  # version list.
  local suites
  mapfile -t suites < <(
    fetch_index "${host}/${codename}/dists/" |
      { grep -oE "llvm-toolchain-${codename}(-[0-9]+)?/" || true; } |
      tr -d '/' |
      sort -uV
  )
  if [[ ${#suites[@]} -eq 0 ]]; then
    fail "llvm: No suites found for '${codename}' at ${host}."
  fi

  echo "llvm: Registering ${#suites[@]} suites (${suites[0]} .. ${suites[-1]})..."
  install_signing_key "${host}/llvm-snapshot.gpg.key" "${keyring}"

  local suite
  {
    echo "# LLVM apt sources for ${distro_id} ${codename}, generated by addAptSources.sh"
    for suite in "${suites[@]}"; do
      echo "deb [signed-by=${keyring}] ${host}/${codename}/ ${suite} main"
      echo "deb-src [signed-by=${keyring}] ${host}/${codename}/ ${suite} main"
    done
  } > "${sources_file}"
  chmod 0644 "${sources_file}"
}

# Prints the architecture segment of the NVIDIA repo path for this machine.
# NVIDIA splits aarch64 by platform: Jetson (Tegra, integrated GPU) packages
# live under arm64 while server-class arm lives under sbsa. That split is a
# platform property apt cannot see, so it is resolved here.
nvidia_repo_architecture() {
  local machine
  machine="$(uname -m)"
  case "${machine}" in
    x86_64)
      echo "x86_64"
      ;;
    aarch64)
      local on_tegra=false
      if [[ -e /etc/nv_tegra_release ]]; then
        on_tegra=true
      elif grep -qa 'tegra' /proc/device-tree/compatible 2> /dev/null; then
        on_tegra=true
      fi
      if ${on_tegra}; then echo "arm64"; else echo "sbsa"; fi
      ;;
    *)
      fail "nvidia: Unsupported architecture '${machine}'."
      ;;
  esac
}

# This is the script form of NVIDIA's own install instructions: fetch the
# cuda-keyring package for your repo and install it. That package owns the
# signing key and the apt source entry. NVIDIA names repo directories by
# concatenated release digits (ubuntu2604, debian13), and the keyring version
# below is the one their instructions name for every distro; bump it here if
# NVIDIA ever bumps it there.
tap_nvidia() {
  local repo_base
  repo_base="https://developer.download.nvidia.com/compute/cuda/repos/${distro_id}${version_id//./}/$(nvidia_repo_architecture)"
  local keyring_url="${repo_base}/cuda-keyring_1.1-1_all.deb"

  echo "nvidia: Installing ${keyring_url}..."
  local temporary_deb
  temporary_deb="$(mktemp --suffix=.deb)"
  if ! curl -fsSL "${keyring_url}" -o "${temporary_deb}"; then
    rm -f "${temporary_deb}"
    fail "nvidia: Cannot fetch ${keyring_url}. NVIDIA may not publish for ${distro_id} ${version_id} (yet)."
  fi
  dpkg -i "${temporary_deb}"
  rm -f "${temporary_deb}"
}

tap_kitware() {
  if [[ "${distro_id}" != "ubuntu" ]]; then
    fail "kitware: The Kitware repository publishes for Ubuntu only (detected: '${distro_id}')."
  fi

  local host="https://apt.kitware.com"
  local keyring="/usr/share/keyrings/kitware-archive-keyring.gpg"

  echo "kitware: Registering ${host}/ubuntu ${codename} main..."
  install_signing_key "${host}/keys/kitware-archive-latest.asc" "${keyring}"
  echo "deb [signed-by=${keyring}] ${host}/ubuntu/ ${codename} main" \
    > /etc/apt/sources.list.d/kitware.list

  # Kitware rotates signing keys via their kitware-archive-keyring package.
  # Install it (after 'apt-get update') to hand key management to apt.
}

# ------------------------------------------------------------------- main ----

assume_yes=false
while getopts ":yh" option; do
  case "${option}" in
    y)
      assume_yes=true
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      usage
      fail "Unknown option: -${OPTARG}"
      ;;
  esac
done
shift $((OPTIND - 1))

taps=("$@")
if [[ ${#taps[@]} -eq 0 ]]; then
  taps=("${ALL_TAPS[@]}")
fi
for tap in "${taps[@]}"; do
  if [[ " ${ALL_TAPS[*]} " != *" ${tap} "* ]]; then
    fail "Unknown tap '${tap}'. Available taps: ${ALL_TAPS[*]}"
  fi
done

if [[ ${EUID} -ne 0 ]]; then
  fail "This script must be run as root (use sudo)."
fi

if [[ ! -r /etc/os-release ]]; then
  fail "Cannot read /etc/os-release to detect OS."
fi
# shellcheck disable=SC1091
. /etc/os-release
distro_id="${ID:-}"
codename="${VERSION_CODENAME:-}"
version_id="${VERSION_ID:-}"

case "${distro_id}" in
  ubuntu | debian) ;;
  *)
    fail "Only Ubuntu and Debian are supported (detected: '${distro_id}')."
    ;;
esac

echo "Detected: ID='${distro_id}', VERSION_ID='${version_id}', VERSION_CODENAME='${codename}'"
echo "Taps to set up: ${taps[*]}"
if ! ${assume_yes}; then
  read -r -p "Proceed with registering these apt sources? [y/N]: " reply
  case "${reply}" in
    [yY] | [yY][eE][sS]) ;;
    *)
      echo "Aborted."
      exit 0
      ;;
  esac
fi

for tap in "${taps[@]}"; do
  "tap_${tap}"
done

echo "Apt sources registered. Run 'apt-get update' before installing."
